name: dtect
channels:
  - conda-forge
dependencies:
  - python=3.8
  # :Infrastructure:
  - pip >= 19.0
  - pep8
  - pylint
  - pycodestyle
  - ipython
  - jupyterlab
  - pyyaml
  # :Scientific computing:
  - numpy >= 1.14
  - scipy >= 1.1.0
  - matplotlib
  - h5py
  - powerlaw
  #- asdf
  # :Astro:
  - astropy
  - galsim
  #- sep
  #- photutils
  # :AI:
  - pip:
   # - numpyro
    - tensorflow==2.2
  # Optional extra:
  #- arviz
