name: "training_data"
ra: 53.11666
dec: -27.80833

frames:
  - band: "fclear"
    scale: 0.03  # arcsec/pixel
    noise: 1.0   # pixels per side
    fwhm: 0.09   # PSF FWHM in arcsec
    n_pix_per_side: 1024  # number of pixels on a side

sources:
  number:
    mu: 1000
    sigma: 500
    min: 0
    max: 3000
  snr:
    powerlaw_index: 1.5
    min: 1.0
    max: 100000.0
  log_size:  # in arcsec
    mu: -1.0
    sigma: 0.4
    min: -1.5
    max: 0.3
  sersic:  # galsim only: n=0.3-6.2
    mu: 1.0
    sigma: 1.5
    min: 0.5
    max: 6.0
  q:
    mu: 0.5
    sigma: 0.25
    min: 0.1
    max: 1.0
